### ISSUE TITLE
Cloud Asset: Add export to BigQuery sample and test

### ISSUE THREAD

**Issue by lvvvvvf** [googleapis/nodejs-asset#212]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/nodejs-asset/issues
  - Search the issues on our "catch-all" repository: https://github.com/googleapis/google-cloud-node
  - Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `@google-cloud/asset` version:

#### Steps to reproduce

 Cloud Asset: We add a new feature which enable user to export assets into Bigquery tables. This is a bug for my cl to add export to BigQuery sample and test

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by sofisl** [comment]
@googleapis/cloud-asset-team

**Comment by bcoe** [comment]
closing as stale.
