### ISSUE TITLE
Samples won't properly capture exceptions

### ISSUE THREAD

**Issue by feywind** [googleapis/nodejs-asset#242]
Just throwing this into the backlog after a discussion on nodejs-pubsub.

Specifically looking at this one, but there may be others:
https://github.com/googleapis/nodejs-asset/blob/master/samples/exportAssets.js

Because the call to the inner async function doesn't await, this won't actually catch and pass on exceptions that happen inside of it, and it'll get an unhandled rejection warning from Node. Simpler repro example:

```
async function main() {
	async function inner() {
		throw new Error("woo!");
	}

	inner();
}

main().catch(console.error);
```

**Comment by bcoe** [comment]
I noticed this in a few places, and was wondering how best to address it, given our goals of a copy pastable sample... did I mention I can't wait for `async`/`await`?

**Comment by sofisl** [comment]
Closing issue since we reassinged it.
