### ISSUE TITLE
cannot get quickstart.js or getBatchAssetHistory.js samples to work

### ISSUE THREAD

**Issue by bcoe** [googleapis/nodejs-asset#424]
I have managed to reproduce flaky tests locally, the root of the problem appears to be that `batchGetAssetsHistory` does not contain a resource in its listing (that obviously exists):

In pantheon 👇 

<img width="994" alt="Screen Shot 2020-11-10 at 9 46 11 AM" src="https://user-images.githubusercontent.com/194609/98711307-af888580-2339-11eb-9bd2-817da9d8bc91.png">

Running sample 👇 

<img width="1522" alt="Screen Shot 2020-11-10 at 9 46 40 AM" src="https://user-images.githubusercontent.com/194609/98711359-bc0cde00-2339-11eb-90a1-646e93689877.png">

I'm guessing this is related to the assets falling outside of the set returned by `readTimeWindow`, but I can't seem to make any values return.

Refs #422

**Comment by fhinkel** [comment]
@bcoe could this be related to the new flake? https://github.com/googleapis/nodejs-asset/issues/478

**Comment by bcoe** [comment]
@fhinkel perhaps? I've completely paged this issue out of memory 😆 

If a test is flaky, I think we should feel comfortable turning it off in some cases -- perhaps this would be the best action in this case?

**Comment by fhinkel** [comment]
It's the quickstart that flakes

**Comment by bcoe** [comment]
@fhinkel perhaps we could get away with just retrying the lookup a few times, it feels like an eventual consistency issue.

**Comment by peter-zheng-g** [comment]
Should be fixed with https://github.com/googleapis/nodejs-asset/pull/547.
